# Generated by Django 2.2.7 on 2020-01-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
