# Generated by Django 2.2.7 on 2020-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0003_auto_20200107_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='purpose',
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
