# Generated by Django 2.2.7 on 2020-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0006_auto_20200501_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
