# Generated by Django 2.2.7 on 2020-05-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sweeper', '0007_usergroup_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='founder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
