# Generated by Django 2.2.7 on 2020-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0008_group_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='hasAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
