# Generated by Django 2.2.7 on 2020-05-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0009_usergroup_hasaccepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='hasAccepted',
            new_name='accepted',
        ),
    ]
