# Generated by Django 2.2.7 on 2020-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0010_auto_20200504_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
